// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: agentlink/v1/agentlink.proto

// How an agent reaches core.
//
// The agent dials core and holds one stream open; everything else travels on
// it, in both directions. Core never has to reach the agent — the agent may be
// behind NAT, in a VM, or on a machine core has no ssh to — so the direction
// of the connection is the agent's, and the direction of the work is core's.
//
// Over the stream core calls the agent's own methods (the same ones a browser
// reaches at /api/rpc/<Method>, as far as the agent allows), and the agent
// sends back the replies and everything its event bus says.

package agentlinkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLink_Connect_FullMethodName = "/superai.agentlink.v1.AgentLink/Connect"
)

// AgentLinkClient is the client API for AgentLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentLinkClient interface {
	// Connect is the agent's one stream. Its first frame is a Hello.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, CoreFrame], error)
}

type agentLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkClient(cc grpc.ClientConnInterface) AgentLinkClient {
	return &agentLinkClient{cc}
}

func (c *agentLinkClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, CoreFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[0], AgentLink_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, CoreFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ConnectClient = grpc.BidiStreamingClient[AgentFrame, CoreFrame]

// AgentLinkServer is the server API for AgentLink service.
// All implementations must embed UnimplementedAgentLinkServer
// for forward compatibility.
type AgentLinkServer interface {
	// Connect is the agent's one stream. Its first frame is a Hello.
	Connect(grpc.BidiStreamingServer[AgentFrame, CoreFrame]) error
	mustEmbedUnimplementedAgentLinkServer()
}

// UnimplementedAgentLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServer struct{}

func (UnimplementedAgentLinkServer) Connect(grpc.BidiStreamingServer[AgentFrame, CoreFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentLinkServer) mustEmbedUnimplementedAgentLinkServer() {}
func (UnimplementedAgentLinkServer) testEmbeddedByValue()                   {}

// UnsafeAgentLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServer will
// result in compilation errors.
type UnsafeAgentLinkServer interface {
	mustEmbedUnimplementedAgentLinkServer()
}

func RegisterAgentLinkServer(s grpc.ServiceRegistrar, srv AgentLinkServer) {
	// If the following call pancis, it indicates UnimplementedAgentLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLink_ServiceDesc, srv)
}

func _AgentLink_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Connect(&grpc.GenericServerStream[AgentFrame, CoreFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ConnectServer = grpc.BidiStreamingServer[AgentFrame, CoreFrame]

// AgentLink_ServiceDesc is the grpc.ServiceDesc for AgentLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "superai.agentlink.v1.AgentLink",
	HandlerType: (*AgentLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentLink_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentlink/v1/agentlink.proto",
}
