// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: agentlink/v1/agentlink.proto

// How an agent reaches core.
//
// The agent dials core and holds one stream open; everything else travels on
// it, in both directions. Core never has to reach the agent — the agent may be
// behind NAT, in a VM, or on a machine core has no ssh to — so the direction
// of the connection is the agent's, and the direction of the work is core's.
//
// Over the stream core calls the agent's own methods (the same ones a browser
// reaches at /api/rpc/<Method>, as far as the agent allows), and the agent
// sends back the replies and everything its event bus says.

package agentlinkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What the agent sends.
type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AgentFrame_Hello
	//	*AgentFrame_Reply
	//	*AgentFrame_Event
	//	*AgentFrame_Pong
	Kind          isAgentFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{0}
}

func (x *AgentFrame) GetKind() isAgentFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AgentFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentFrame) GetReply() *Reply {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *AgentFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentFrame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Kind.(*AgentFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isAgentFrame_Kind interface {
	isAgentFrame_Kind()
}

type AgentFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentFrame_Reply struct {
	Reply *Reply `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

type AgentFrame_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type AgentFrame_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*AgentFrame_Hello) isAgentFrame_Kind() {}

func (*AgentFrame_Reply) isAgentFrame_Kind() {}

func (*AgentFrame_Event) isAgentFrame_Kind() {}

func (*AgentFrame_Pong) isAgentFrame_Kind() {}

// What core sends.
type CoreFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*CoreFrame_Welcome
	//	*CoreFrame_Call
	//	*CoreFrame_Ping
	Kind          isCoreFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreFrame) Reset() {
	*x = CoreFrame{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrame) ProtoMessage() {}

func (x *CoreFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrame.ProtoReflect.Descriptor instead.
func (*CoreFrame) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{1}
}

func (x *CoreFrame) GetKind() isCoreFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *CoreFrame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*CoreFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *CoreFrame) GetCall() *Call {
	if x != nil {
		if x, ok := x.Kind.(*CoreFrame_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *CoreFrame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*CoreFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isCoreFrame_Kind interface {
	isCoreFrame_Kind()
}

type CoreFrame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type CoreFrame_Call struct {
	Call *Call `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type CoreFrame_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*CoreFrame_Welcome) isCoreFrame_Kind() {}

func (*CoreFrame_Call) isCoreFrame_Kind() {}

func (*CoreFrame_Ping) isCoreFrame_Kind() {}

// Hello says who the agent is and what it can run. Sent first, and again
// whenever that changes; each one replaces the last.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name core addresses it by: "claude.<name>", and the hive view.
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host    string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Os      string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch    string `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Coding CLIs installed there: "claude", "codex", ...
	Clis []string `protobuf:"bytes,6,rep,name=clis,proto3" json:"clis,omitempty"`
	// Other agents it can reach and run for core: openclaw, hermes, ...
	Agents        []*NamedAgent `protobuf:"bytes,7,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetClis() []string {
	if x != nil {
		return x.Clis
	}
	return nil
}

func (x *Hello) GetAgents() []*NamedAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type NamedAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	About         string                 `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedAgent) Reset() {
	*x = NamedAgent{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedAgent) ProtoMessage() {}

func (x *NamedAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedAgent.ProtoReflect.Descriptor instead.
func (*NamedAgent) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{3}
}

func (x *NamedAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedAgent) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

type Welcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name core has it under.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Call runs one of the agent's methods. Arguments and result are the JSON the
// method takes and returns over /api/rpc, so the two surfaces cannot differ.
type Call struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// A JSON array, one element per argument.
	ArgsJson      string `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{5}
}

func (x *Call) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Call) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Call) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type Reply struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResultJson string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Set when the method failed; result_json is then empty.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reply) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Reply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Event is one thing the agent's event bus said (cli:run, cli:event,
// tool:approval, ...), as name and JSON payload.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixMs      int64                  `protobuf:"varint,1,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixMs      int64                  `protobuf:"varint,1,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

var File_agentlink_v1_agentlink_proto protoreflect.FileDescriptor

const file_agentlink_v1_agentlink_proto_rawDesc = "" +
	"\n" +
	"\x1cagentlink/v1/agentlink.proto\x12\x14superai.agentlink.v1\"\xe5\x01\n" +
	"\n" +
	"AgentFrame\x123\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.superai.agentlink.v1.HelloH\x00R\x05hello\x123\n" +
	"\x05reply\x18\x02 \x01(\v2\x1b.superai.agentlink.v1.ReplyH\x00R\x05reply\x123\n" +
	"\x05event\x18\x03 \x01(\v2\x1b.superai.agentlink.v1.EventH\x00R\x05event\x120\n" +
	"\x04pong\x18\x04 \x01(\v2\x1a.superai.agentlink.v1.PongH\x00R\x04pongB\x06\n" +
	"\x04kind\"\xb2\x01\n" +
	"\tCoreFrame\x129\n" +
	"\awelcome\x18\x01 \x01(\v2\x1d.superai.agentlink.v1.WelcomeH\x00R\awelcome\x120\n" +
	"\x04call\x18\x02 \x01(\v2\x1a.superai.agentlink.v1.CallH\x00R\x04call\x120\n" +
	"\x04ping\x18\x03 \x01(\v2\x1a.superai.agentlink.v1.PingH\x00R\x04pingB\x06\n" +
	"\x04kind\"\xbb\x01\n" +
	"\x05Hello\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04clis\x18\x06 \x03(\tR\x04clis\x128\n" +
	"\x06agents\x18\a \x03(\v2 .superai.agentlink.v1.NamedAgentR\x06agents\"6\n" +
	"\n" +
	"NamedAgent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05about\x18\x02 \x01(\tR\x05about\"\x1d\n" +
	"\aWelcome\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x04Call\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"N\n" +
	"\x05Reply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\">\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"$\n" +
	"\x04Ping\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x01 \x01(\x03R\batUnixMs\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x01 \x01(\x03R\batUnixMs2]\n" +
	"\tAgentLink\x12P\n" +
	"\aConnect\x12 .superai.agentlink.v1.AgentFrame\x1a\x1f.superai.agentlink.v1.CoreFrame(\x010\x01BAZ?github.com/liliang-cn/superai/internal/agentlink/pb;agentlinkpbb\x06proto3"

var (
	file_agentlink_v1_agentlink_proto_rawDescOnce sync.Once
	file_agentlink_v1_agentlink_proto_rawDescData []byte
)

func file_agentlink_v1_agentlink_proto_rawDescGZIP() []byte {
	file_agentlink_v1_agentlink_proto_rawDescOnce.Do(func() {
		file_agentlink_v1_agentlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)))
	})
	return file_agentlink_v1_agentlink_proto_rawDescData
}

var file_agentlink_v1_agentlink_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agentlink_v1_agentlink_proto_goTypes = []any{
	(*AgentFrame)(nil), // 0: superai.agentlink.v1.AgentFrame
	(*CoreFrame)(nil),  // 1: superai.agentlink.v1.CoreFrame
	(*Hello)(nil),      // 2: superai.agentlink.v1.Hello
	(*NamedAgent)(nil), // 3: superai.agentlink.v1.NamedAgent
	(*Welcome)(nil),    // 4: superai.agentlink.v1.Welcome
	(*Call)(nil),       // 5: superai.agentlink.v1.Call
	(*Reply)(nil),      // 6: superai.agentlink.v1.Reply
	(*Event)(nil),      // 7: superai.agentlink.v1.Event
	(*Ping)(nil),       // 8: superai.agentlink.v1.Ping
	(*Pong)(nil),       // 9: superai.agentlink.v1.Pong
}
var file_agentlink_v1_agentlink_proto_depIdxs = []int32{
	2, // 0: superai.agentlink.v1.AgentFrame.hello:type_name -> superai.agentlink.v1.Hello
	6, // 1: superai.agentlink.v1.AgentFrame.reply:type_name -> superai.agentlink.v1.Reply
	7, // 2: superai.agentlink.v1.AgentFrame.event:type_name -> superai.agentlink.v1.Event
	9, // 3: superai.agentlink.v1.AgentFrame.pong:type_name -> superai.agentlink.v1.Pong
	4, // 4: superai.agentlink.v1.CoreFrame.welcome:type_name -> superai.agentlink.v1.Welcome
	5, // 5: superai.agentlink.v1.CoreFrame.call:type_name -> superai.agentlink.v1.Call
	8, // 6: superai.agentlink.v1.CoreFrame.ping:type_name -> superai.agentlink.v1.Ping
	3, // 7: superai.agentlink.v1.Hello.agents:type_name -> superai.agentlink.v1.NamedAgent
	0, // 8: superai.agentlink.v1.AgentLink.Connect:input_type -> superai.agentlink.v1.AgentFrame
	1, // 9: superai.agentlink.v1.AgentLink.Connect:output_type -> superai.agentlink.v1.CoreFrame
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_agentlink_v1_agentlink_proto_init() }
func file_agentlink_v1_agentlink_proto_init() {
	if File_agentlink_v1_agentlink_proto != nil {
		return
	}
	file_agentlink_v1_agentlink_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentFrame_Hello)(nil),
		(*AgentFrame_Reply)(nil),
		(*AgentFrame_Event)(nil),
		(*AgentFrame_Pong)(nil),
	}
	file_agentlink_v1_agentlink_proto_msgTypes[1].OneofWrappers = []any{
		(*CoreFrame_Welcome)(nil),
		(*CoreFrame_Call)(nil),
		(*CoreFrame_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentlink_v1_agentlink_proto_goTypes,
		DependencyIndexes: file_agentlink_v1_agentlink_proto_depIdxs,
		MessageInfos:      file_agentlink_v1_agentlink_proto_msgTypes,
	}.Build()
	File_agentlink_v1_agentlink_proto = out.File
	file_agentlink_v1_agentlink_proto_goTypes = nil
	file_agentlink_v1_agentlink_proto_depIdxs = nil
}
