// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AddRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddSchedule'](arg1, arg2, arg3, arg4);
}

export function AskRemoteAgent(arg1, arg2) {
  return window['go']['app']['App']['AskRemoteAgent'](arg1, arg2);
}

export function Attention() {
  return window['go']['app']['App']['Attention']();
}

export function CLIProxyAccounts() {
  return window['go']['app']['App']['CLIProxyAccounts']();
}

export function CLIProxyLogin(arg1, arg2) {
  return window['go']['app']['App']['CLIProxyLogin'](arg1, arg2);
}

export function CLIProxyProviders() {
  return window['go']['app']['App']['CLIProxyProviders']();
}

export function CLIProxySetAccountEnabled(arg1, arg2) {
  return window['go']['app']['App']['CLIProxySetAccountEnabled'](arg1, arg2);
}

export function CLIProxySignOut(arg1) {
  return window['go']['app']['App']['CLIProxySignOut'](arg1);
}

export function CLIProxyStatus() {
  return window['go']['app']['App']['CLIProxyStatus']();
}

export function CLIProxySubmitPrompt(arg1) {
  return window['go']['app']['App']['CLIProxySubmitPrompt'](arg1);
}

export function CLIRunDetail(arg1) {
  return window['go']['app']['App']['CLIRunDetail'](arg1);
}

export function CLIRuns() {
  return window['go']['app']['App']['CLIRuns']();
}

export function CancelAllChats() {
  return window['go']['app']['App']['CancelAllChats']();
}

export function CancelCLIRun(arg1) {
  return window['go']['app']['App']['CancelCLIRun'](arg1);
}

export function CancelChat(arg1) {
  return window['go']['app']['App']['CancelChat'](arg1);
}

export function CancelScheduledRun(arg1) {
  return window['go']['app']['App']['CancelScheduledRun'](arg1);
}

export function ChatHistory(arg1) {
  return window['go']['app']['App']['ChatHistory'](arg1);
}

export function ChatSessions() {
  return window['go']['app']['App']['ChatSessions']();
}

export function CheckRemoteAgents() {
  return window['go']['app']['App']['CheckRemoteAgents']();
}

export function ClearNotifications() {
  return window['go']['app']['App']['ClearNotifications']();
}

export function Dashboard() {
  return window['go']['app']['App']['Dashboard']();
}

export function Dashboards() {
  return window['go']['app']['App']['Dashboards']();
}

export function DeleteChatSession(arg1) {
  return window['go']['app']['App']['DeleteChatSession'](arg1);
}

export function DeleteDashboard(arg1) {
  return window['go']['app']['App']['DeleteDashboard'](arg1);
}

export function DeleteScheduledPrompt(arg1) {
  return window['go']['app']['App']['DeleteScheduledPrompt'](arg1);
}

export function DeleteStandingAgent(arg1) {
  return window['go']['app']['App']['DeleteStandingAgent'](arg1);
}

export function Deliverables(arg1) {
  return window['go']['app']['App']['Deliverables'](arg1);
}

export function Doctor() {
  return window['go']['app']['App']['Doctor']();
}

export function EmitAvatarTest(arg1) {
  return window['go']['app']['App']['EmitAvatarTest'](arg1);
}

export function ExportWorkspaceFile(arg1) {
  return window['go']['app']['App']['ExportWorkspaceFile'](arg1);
}

export function ExternalAgentsStatus() {
  return window['go']['app']['App']['ExternalAgentsStatus']();
}

export function FollowUpCLIRun(arg1, arg2) {
  return window['go']['app']['App']['FollowUpCLIRun'](arg1, arg2);
}

export function ForgetHive(arg1) {
  return window['go']['app']['App']['ForgetHive'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GraphView() {
  return window['go']['app']['App']['GraphView']();
}

export function HiveLinkStatus() {
  return window['go']['app']['App']['HiveLinkStatus']();
}

export function HiveLinks() {
  return window['go']['app']['App']['HiveLinks']();
}

export function HiveMembers() {
  return window['go']['app']['App']['HiveMembers']();
}

export function HiveRetire(arg1, arg2) {
  return window['go']['app']['App']['HiveRetire'](arg1, arg2);
}

export function HiveSpawn(arg1) {
  return window['go']['app']['App']['HiveSpawn'](arg1);
}

export function HiveStatus() {
  return window['go']['app']['App']['HiveStatus']();
}

export function HiveTaskDetail(arg1) {
  return window['go']['app']['App']['HiveTaskDetail'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['app']['App']['ImportCSV'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['app']['App']['ImportFiles'](arg1);
}

export function ImportPastedFile(arg1, arg2) {
  return window['go']['app']['App']['ImportPastedFile'](arg1, arg2);
}

export function InstallMCPServer(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InstallMCPServer'](arg1, arg2, arg3, arg4);
}

export function InstallSkill(arg1, arg2) {
  return window['go']['app']['App']['InstallSkill'](arg1, arg2);
}

export function Life() {
  return window['go']['app']['App']['Life']();
}

export function LinkHive(arg1, arg2) {
  return window['go']['app']['App']['LinkHive'](arg1, arg2);
}

export function LinkSuperAI(arg1, arg2, arg3) {
  return window['go']['app']['App']['LinkSuperAI'](arg1, arg2, arg3);
}

export function LinkedAgents() {
  return window['go']['app']['App']['LinkedAgents']();
}

export function LinkedSuperAIs() {
  return window['go']['app']['App']['LinkedSuperAIs']();
}

export function LongRunList() {
  return window['go']['app']['App']['LongRunList']();
}

export function LongRunStart(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['LongRunStart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LongRunState(arg1) {
  return window['go']['app']['App']['LongRunState'](arg1);
}

export function LongRunStop(arg1) {
  return window['go']['app']['App']['LongRunStop'](arg1);
}

export function MCP() {
  return window['go']['app']['App']['MCP']();
}

export function MarkNotificationsRead(arg1) {
  return window['go']['app']['App']['MarkNotificationsRead'](arg1);
}

export function MemoryRecall(arg1) {
  return window['go']['app']['App']['MemoryRecall'](arg1);
}

export function MemorySkills() {
  return window['go']['app']['App']['MemorySkills']();
}

export function Notifications() {
  return window['go']['app']['App']['Notifications']();
}

export function Notify(arg1, arg2, arg3) {
  return window['go']['app']['App']['Notify'](arg1, arg2, arg3);
}

export function OpenInBrowser() {
  return window['go']['app']['App']['OpenInBrowser']();
}

export function OpenWorkspaceFileExternal(arg1) {
  return window['go']['app']['App']['OpenWorkspaceFileExternal'](arg1);
}

export function PairPhone() {
  return window['go']['app']['App']['PairPhone']();
}

export function PairedDevices() {
  return window['go']['app']['App']['PairedDevices']();
}

export function PauseStandingAgent(arg1) {
  return window['go']['app']['App']['PauseStandingAgent'](arg1);
}

export function PendingToolApprovals() {
  return window['go']['app']['App']['PendingToolApprovals']();
}

export function PetStage(arg1, arg2) {
  return window['go']['app']['App']['PetStage'](arg1, arg2);
}

export function PickFiles() {
  return window['go']['app']['App']['PickFiles']();
}

export function PreviewPrompt(arg1, arg2) {
  return window['go']['app']['App']['PreviewPrompt'](arg1, arg2);
}

export function Pulse() {
  return window['go']['app']['App']['Pulse']();
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['app']['App']['ReadWorkspaceFile'](arg1);
}

export function ReadWorkspaceFileDataURL(arg1) {
  return window['go']['app']['App']['ReadWorkspaceFileDataURL'](arg1);
}

export function RefreshDashboard(arg1) {
  return window['go']['app']['App']['RefreshDashboard'](arg1);
}

export function Remote(arg1, arg2) {
  return window['go']['app']['App']['Remote'](arg1, arg2);
}

export function RemoteAgentNames() {
  return window['go']['app']['App']['RemoteAgentNames']();
}

export function RemoveMCPServer(arg1) {
  return window['go']['app']['App']['RemoveMCPServer'](arg1);
}

export function RemoveSkill(arg1) {
  return window['go']['app']['App']['RemoveSkill'](arg1);
}

export function RenameDashboard(arg1, arg2) {
  return window['go']['app']['App']['RenameDashboard'](arg1, arg2);
}

export function ResolveToolApproval(arg1, arg2) {
  return window['go']['app']['App']['ResolveToolApproval'](arg1, arg2);
}

export function ResumeStandingAgent(arg1) {
  return window['go']['app']['App']['ResumeStandingAgent'](arg1);
}

export function RunAgentLink(arg1, arg2) {
  return window['go']['app']['App']['RunAgentLink'](arg1, arg2);
}

export function RunScheduledPromptNow(arg1) {
  return window['go']['app']['App']['RunScheduledPromptNow'](arg1);
}

export function SaveDashboard(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveDashboard'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveStandingAgent(arg1) {
  return window['go']['app']['App']['SaveStandingAgent'](arg1);
}

export function ScheduleFromText(arg1) {
  return window['go']['app']['App']['ScheduleFromText'](arg1);
}

export function SchedulePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SchedulePrompt'](arg1, arg2, arg3, arg4);
}

export function ScheduledPrompts() {
  return window['go']['app']['App']['ScheduledPrompts']();
}

export function SearchMCPServers(arg1) {
  return window['go']['app']['App']['SearchMCPServers'](arg1);
}

export function SearchSkills(arg1) {
  return window['go']['app']['App']['SearchSkills'](arg1);
}

export function SendChat(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendChat'](arg1, arg2, arg3);
}

export function SetDashboardCron(arg1, arg2) {
  return window['go']['app']['App']['SetDashboardCron'](arg1, arg2);
}

export function SetScheduledPromptEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetScheduledPromptEnabled'](arg1, arg2);
}

export function SetUIRules(arg1) {
  return window['go']['app']['App']['SetUIRules'](arg1);
}

export function SetWindowTheme(arg1) {
  return window['go']['app']['App']['SetWindowTheme'](arg1);
}

export function Skills() {
  return window['go']['app']['App']['Skills']();
}

export function StandingAgents() {
  return window['go']['app']['App']['StandingAgents']();
}

export function StandingReports(arg1) {
  return window['go']['app']['App']['StandingReports'](arg1);
}

export function StandingWakes(arg1) {
  return window['go']['app']['App']['StandingWakes'](arg1);
}

export function StartCLIRun(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartCLIRun'](arg1, arg2, arg3, arg4, arg5);
}

export function StartYoloMode() {
  return window['go']['app']['App']['StartYoloMode']();
}

export function StopYoloMode() {
  return window['go']['app']['App']['StopYoloMode']();
}

export function TakeOver(arg1, arg2, arg3) {
  return window['go']['app']['App']['TakeOver'](arg1, arg2, arg3);
}

export function TestWebhook() {
  return window['go']['app']['App']['TestWebhook']();
}

export function TitleBarDoubleClick() {
  return window['go']['app']['App']['TitleBarDoubleClick']();
}

export function ToolApprovalInfo(arg1) {
  return window['go']['app']['App']['ToolApprovalInfo'](arg1);
}

export function TraceLines(arg1, arg2) {
  return window['go']['app']['App']['TraceLines'](arg1, arg2);
}

export function UnlinkHive() {
  return window['go']['app']['App']['UnlinkHive']();
}

export function UnlinkSuperAI(arg1) {
  return window['go']['app']['App']['UnlinkSuperAI'](arg1);
}

export function UnpairDevice(arg1) {
  return window['go']['app']['App']['UnpairDevice'](arg1);
}

export function UnreadNotifications() {
  return window['go']['app']['App']['UnreadNotifications']();
}

export function Upcoming() {
  return window['go']['app']['App']['Upcoming']();
}

export function UseHive(arg1) {
  return window['go']['app']['App']['UseHive'](arg1);
}

export function WakeStandingAgent(arg1, arg2) {
  return window['go']['app']['App']['WakeStandingAgent'](arg1, arg2);
}
